apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 4
  template: 
    metadata:       
      labels:
        app: api
    spec:            
      containers:
      - name: api
        image: dkendy/calculoapi:{{tag}}
        ports:
        - containerPort: 80
        imagePullPolicy: Always